version: '3'

services:
  app:
    container_name: poplog-producer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 10000:10000
    volumes:
      - ./:/home/app/
    networks:
      - poplog-network

networks:
  poplog-network:
    external:
      name: poplog_network